# Generated by Django 3.0.8 on 2020-08-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kategorii', models.PositiveIntegerField()),
                ('nazwa', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_klienta', models.PositiveIntegerField()),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_klienta', models.PositiveIntegerField()),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produkty_Zamowienia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zamowienia', models.PositiveIntegerField()),
                ('id_produktu', models.PositiveIntegerField()),
                ('ilosc', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sprzedawca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sprzedawcy', models.PositiveIntegerField()),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zamowienia', models.PositiveIntegerField()),
                ('id_klienta', models.PositiveIntegerField()),
                ('id_sprzedawcy', models.PositiveIntegerField()),
                ('data', models.DateField()),
            ],
        ),
    ]
