# Generated by Django 3.0.8 on 2020-08-03 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plots_graphs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='id_klienta',
            new_name='id_produktu',
        ),
    ]
