# Generated by Django 3.0.8 on 2020-08-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots_graphs', '0002_auto_20200804_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkt',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='nazwisko',
        ),
        migrations.AddField(
            model_name='produkt',
            name='cena',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='id_kategorii',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AddField(
            model_name='produkt',
            name='nazwa',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
